name: Daily Bitcoin Forecast

on:
  schedule:
    - cron: "17 6 * * *"   # runs every day at 06:17 UTC
  workflow_dispatch:        # allow manual run
  push:
    branches: [ main ]

jobs:
  run-forecast:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python - << 'PY'
          import nltk
          nltk.download("vader_lexicon", quiet=True)
          PY

      - name: Run forecast
        run: python -u bitcoin_forecast.py

      - name: Upload outputs (CSVs/PNGs/JSON)
        uses: actions/upload-artifact@v4
        with:
          name: btc-forecast-outputs
          path: outputs/**

           - name: Push to Overleaf (publish report + figures)
        run: |
          set -e
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@users.noreply.github.com"
          # Add the Overleaf remote (stored as a secret)
          git remote add overleaf "${{ secrets.OVERLEAF_GIT_URL }}"
          # Create a temporary tree with only the report and outputs
          rm -rf /tmp/overleaf && mkdir -p /tmp/overleaf
          cp -r report /tmp/overleaf/
          cp -r outputs /tmp/overleaf/
          cd /tmp/overleaf
          git init
          git add -A
          git commit -m "Auto-publish $(date -u +'%Y-%m-%d %H:%M UTC')"
          # Overleaf’s default branch is usually 'master'
          git branch -M master
          git remote add overleaf "${{ secrets.OVERLEAF_GIT_URL }}"
          git push -f overleaf master
