name: Daily Bitcoin Forecast

on:
  schedule:
    - cron: '17 6 * * *' # every day at 06:17 UTC
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  run-forecast:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python - << 'PY'
          import nltk
          nltk.download("vader_lexicon", quiet=True)
          PY

      - name: Run forecast (generates report/inputs.tex + PNGs)
        env:
          USE_FINBERT: 'false'
          USE_GNEWS: 'false'   # CI often blocks this
          USE_REDDIT: 'false'  # reddit RSS is flaky on CI
          USE_RSS: 'true'
          USE_GDELT: 'true'
          SCRAPE_DAYS: '30'
        run: python -u bitcoin_forecast.py

      - name: Verify generated report assets
        run: |
          echo "Tree under report/:"
          ls -lah report || true
          echo "Tree under report/outputs/:"
          ls -lah report/outputs || true

          test -f report/inputs.tex || (echo "❌ inputs.tex missing -> forecast step failed"; exit 1)
          test -f report/outputs/fig_price_forecast.png || (echo "❌ fig_price_forecast.png missing"; exit 1)


      - name: Compile Beamer PDF (XeLaTeX)
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
          working_directory: report
          latexmk_use_xelatex: true

      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: bitcoin-forecast-report
          path: report/main.pdf

      - name: Upload outputs (PNGs/JSON/CSVs)
        uses: actions/upload-artifact@v4
        with:
          name: btc-forecast-outputs
          path: report/outputs/**

      - name: Push to Overleaf (publish report + figures)
        env:
          OVERLEAF_URL: ${{ secrets.OVERLEAF_GIT_URL }}
        if: ${{ env.OVERLEAF_URL != '' }}
        shell: bash
        run: |
          set -eo pipefail

          url="${OVERLEAF_URL}"
          echo "::add-mask::$url"

          tmp="$(mktemp -d)"
          git clone --depth 1 "$url" "$tmp/overleaf"

          rsync -a --delete --exclude ".git" report/ "$tmp/overleaf/"

          cd "$tmp/overleaf"
          git config user.name "GitHub Actions"
          git config user.email "actions@users.noreply.github.com"

          if git diff --quiet && [ -z "$(git ls-files --others --exclude-standard)" ]; then
            echo "No changes to publish."
            exit 0
          fi

          git add -A
          ts=$(date -u +%Y-%m-%dT%H:%MZ)
          git commit -m "Auto-publish ${ts}"
          git push origin HEAD:master
